### ISSUE TITLE
导入报错

### ISSUE THREAD

**Issue by wdq123550** [amisare/NNPopObjc#2]
![image](https://user-images.githubusercontent.com/20955893/83937424-07591880-a7ff-11ea-8d96-7e1f0207e351.png)
难道和其他第三方库冲突了？

**Comment by wdq123550** [comment]
Undefined symbols for architecture arm64:
  "rcrtc::MacBaseSocketServer::UnregisterSocket(rcrtc::MacAsyncSocket*)", referenced from:
      rcrtc::MacAsyncSocket::Close() in RongIMLib(macasyncsocket.o)
  "rcrtc::MacBaseSocketServer::RegisterSocket(rcrtc::MacAsyncSocket*)", referenced from:
      rcrtc::MacAsyncSocket::Initialize(int) in RongIMLib(macasyncsocket.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by amisare** [comment]
1. NNPopObjc 没有依赖其他第三方库。
2. 集成 NNPopObjc 的时候 podspec 中
`s.user_target_xcconfig = {'OTHER_LDFLAGS' => '-all_load'}`
会要求链接所有符号，猜测是链接的符号对应没有实现。

**Comment by wdq123550** [comment]
使用Carthage导入不会出现上述问题。此问题关闭
