### ISSUE TITLE
语法报错

### ISSUE THREAD

**Issue by wdq123550** [amisare/NNPopObjc#3]
![image](https://user-images.githubusercontent.com/20955893/83937858-ebf00c80-a802-11ea-93b4-bb4e0633daa1.png)
![image](https://user-images.githubusercontent.com/20955893/83937863-f1e5ed80-a802-11ea-97df-ca9eee330da8.png)
请看图片

**Comment by amisare** [comment]
`nn_extension` 前加上 `@`，如下：

```
@nn_extension(gg)

- (void)gg {
    
}

@end
```

**Comment by wdq123550** [comment]
明白！
