### ISSUE TITLE
提示问题

### ISSUE THREAD

**Issue by wdq123550** [amisare/NNPopObjc#4]
图片1：![image](https://user-images.githubusercontent.com/20955893/84114793-8b114000-aa5f-11ea-886d-ed8ec2a3525d.png)
图片2：![image](https://user-images.githubusercontent.com/20955893/84114860-a67c4b00-aa5f-11ea-8027-5a9467f70a02.png)

输入@nn没有智能提示
但是输出nn就有，这样很容易忘记在前面加@

**Comment by amisare** [comment]
确实在加上 `@` 会导致 Xcode 联想缺失。增加了开头的 `@`，为了保持与原始语言语法的一致性。

解决联想缺失问题，可以通过在 Xcode 中添加 Snippet 来实现。

![image](https://user-images.githubusercontent.com/6335968/84117355-fc52f200-aa63-11ea-9b9c-f878caacea8c.png)

![image](https://user-images.githubusercontent.com/6335968/84117524-3cb27000-aa64-11ea-956d-248fa518db91.png)
