### ISSUE TITLE
在@nn_extension里面输入if和forin没有自动补全功能

### ISSUE THREAD

**Issue by wdq123550** [amisare/NNPopObjc#5]

**Comment by wdq123550** [comment]
![image](https://user-images.githubusercontent.com/20955893/84459052-0d387900-ac99-11ea-9b53-9887d0098cd1.png)
![image](https://user-images.githubusercontent.com/20955893/84459070-1b869500-ac99-11ea-9ef7-a46383920b13.png)

**Comment by amisare** [comment]
你描述的情况，受限于 IDE ，暂时没有太好的解决方法。
